modLoader="javafml"
loaderVersion="*"
license="All Rights Reserved"
issueTrackerURL="https://github.com/Serilum/.issue-tracker/labels/Mod:%20Hide%20Experimental%20Warning"
iconFile="icon.png"

[[mods]]
modId="hideexperimentalwarning"
version="1.3"
displayName="Hide Experimental Warning"
displayURL="https://serilum.com/mod/hide-experimental-warning"
authors="Serilum"
description='''Hides the Experimental Settings Warning when trying to create or load a perfectly fine modded world.
'''
credits='''Thank you very much to my Membership sponsors for supporting the development of this mod:  

Andrean Olgo, AnyankaT, aternosorg, Cherriesaurus, Linda Jansen, MWS, Tyler Behl   

If you would like to contribute too, check out https://serilum.com/donate Appreciate it! <3   
'''

[[dependencies.hideexperimentalwarning]]
    modId="collective"
    type="required"
    versionRange="[8.40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.hideexperimentalwarning]]
    modId="minecraft"
    type="required"
    versionRange="[26.3]"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "hideexperimentalwarning.mixins.json"